server:
  port: 8082
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 25MB
      file-size-threshold: 25MB
  thymeleaf:
    enabled: true
    cache: false          # Disable cache during development
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet.content-type: text/html
file:
  upload-dir: ./test-uploads

